# Generated by Django 5.1.6 on 2025-02-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
