# Generated by Django 5.1.6 on 2025-03-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='doctor_images/'),
        ),
    ]
